--------------------------------------------------------
--  File created - Friday-March-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESSES
--------------------------------------------------------

  CREATE TABLE "ADDRESSES" 
   (	"ADDRID" VARCHAR2(20 BYTE), 
	"STREETADDR" VARCHAR2(100 BYTE), 
	"APTNUMBER" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"MOBILEPHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADDRGEOLOC
--------------------------------------------------------

  CREATE TABLE "ADDRGEOLOC" 
   (	"ADDRID" VARCHAR2(20 BYTE), 
	"GEOLOC" "SDO_GEOMETRY"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "CUSTOMERS" 
   (	"USEREMAIL" VARCHAR2(100 BYTE), 
	"CUSTPASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIKEREVIEW
--------------------------------------------------------

  CREATE TABLE "LIKEREVIEW" 
   (	"CUSTOMEREMAIL" VARCHAR2(100 BYTE), 
	"REVIEWID" VARCHAR2(20 BYTE), 
	"LIKETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MDRT_125D1$
--------------------------------------------------------

  CREATE TABLE "MDRT_125D1$" 
   (	"NODE_ID" NUMBER, 
	"NODE_LEVEL" NUMBER, 
	"INFO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 2 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("INFO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  MONITORING ;
--------------------------------------------------------
--  DDL for Table ORDERPRODUCTQTY
--------------------------------------------------------

  CREATE TABLE "ORDERPRODUCTQTY" 
   (	"ORDERID" VARCHAR2(20 BYTE), 
	"PRODUCTID" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "ORDERS" 
   (	"ORDERID" VARCHAR2(20 BYTE), 
	"SHIPPEDTIME" DATE, 
	"ESTIARRITIME" DATE, 
	"SIGNEDTIME" DATE, 
	"TOTALPRICE" NUMBER, 
	"TRACKINGNUM" VARCHAR2(20 BYTE), 
	"PLACETIME" DATE, 
	"ACCNUM" VARCHAR2(20 BYTE), 
	"EXPDATE" DATE, 
	"CSC" VARCHAR2(10 BYTE), 
	"FILLTIME" DATE, 
	"CUSTOMEREMAIL" VARCHAR2(100 BYTE), 
	"SHIPADDR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHOTOS
--------------------------------------------------------

  CREATE TABLE "PHOTOS" 
   (	"PHOTOID" VARCHAR2(20 BYTE), 
	"TAKEN_TIME" DATE, 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTPHOTO
--------------------------------------------------------

  CREATE TABLE "PRODUCTPHOTO" 
   (	"PRODUCTID" VARCHAR2(20 BYTE), 
	"PHOTOID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "PRODUCTS" 
   (	"PRODUCTID" VARCHAR2(20 BYTE), 
	"PRONAME" VARCHAR2(100 BYTE), 
	"PROCATEGORY" VARCHAR2(50 BYTE), 
	"BRAND" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"STOCKQTY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTSELLER
--------------------------------------------------------

  CREATE TABLE "PRODUCTSELLER" 
   (	"SELLEREMAIL" VARCHAR2(100 BYTE), 
	"PRODUCTID" VARCHAR2(20 BYTE), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "REVIEWS" 
   (	"REVIEWID" VARCHAR2(20 BYTE), 
	"AUTHORID" VARCHAR2(100 BYTE), 
	"RATING" NUMBER, 
	"COMTENT" VARCHAR2(1000 BYTE), 
	"PRODUCTID" VARCHAR2(20 BYTE), 
	"POSTTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SELLERS
--------------------------------------------------------

  CREATE TABLE "SELLERS" 
   (	"USEREMAIL" VARCHAR2(100 BYTE), 
	"SELLERPASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USEREMAIL" VARCHAR2(100 BYTE), 
	"BIRTHDATE" DATE, 
	"BIRTHMONTH" VARCHAR2(10 BYTE), 
	"AGE" NUMBER, 
	"FNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"ACCNUMBER" VARCHAR2(20 BYTE), 
	"EXPDATE" DATE, 
	"CSC" VARCHAR2(20 BYTE), 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"JOINTIME" DATE, 
	"PHOTOID" VARCHAR2(20 BYTE), 
	"ADDRID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into XINSHI.ADDRESSES
SET DEFINE OFF;
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A1','W Jefferson','655','Los Angeles','90007','CA',460,434,'1-213-995-2968');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A2','Roosevelt AVE','124-02','Flushing','11368','NY',165,195,'1-299-995-3009');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A3','Melrose Pl','8446','Los Angeles','90069','CA',770,165,'1-213-995-9700');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A4','E Main St','1300','Alhambra','91801','CA',450,455,'1-213-995-3131');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A5','S Figueroa St.','3335','Los Angeles','90007','CA',310,277,'1-213-995-6183');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A6','Broadway ','2400','Santa Monica','90404','CA',333,157,'1-213-995-2220');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A7','South Lemon Street','1445','Fullerton','92832','CA',470,430,'1-213-995-6210');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A8','Marine Drive','2300','San Francisco','94129','CA',45,407,'1-213-995-3041');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A9','Statue of Liberty National Monumentmore','1','Ney York','10004','NY',530,345,'1-299-995-4796');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A10','Griffith Park','2','Los Angeles','90027','CA',128,246,'1-213-995-6600');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A11','Magic Mountain Parkway','26101','Valencia','91355','CA',372,334,'1-213-995-9960');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A12','Massachusetts Ave','1350','Cambridge','2138','MA',429,280,'1-211-995-6126');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A13','Hilgard Avenue','405','Los Angeles','90095','CA',22,368,'1-213-995-6633');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A14','Massachusetts Avenue','77','Cambridge','2139','MA',129,259,'1-211-995-9980');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A15','Trousdale Pkwy','3607','Los Angeles','90089','CA',725,339,'1-213-995-6268');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A16','Wilshire Blvd','5757','Los Angeles','90036','CA',623,273,'1-213-995-6640');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A17',' N La Brea Ave','1133','West Hollywood','90038','CA',11,135,'1-213-995-6205');
Insert into XINSHI.ADDRESSES (ADDRID,STREETADDR,APTNUMBER,CITY,ZIP,STATE,LATITUDE,LONGITUDE,MOBILEPHONE) values ('A18','Shattuck Avenue','1890','Berkeley','94709','CA',502,288,'1-213-995-8792');
REM INSERTING into XINSHI.ADDRGEOLOC
SET DEFINE OFF;
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A1',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(460,434,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A2',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(165,195,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A3',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(770,165,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A4',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(450,455,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A5',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(310,277,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A6',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(333,157,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A7',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(470,430,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A8',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(45,407,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A9',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(530,345,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A10',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(128,246,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A11',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(372,334,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A12',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(429,280,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A13',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(22,368,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A14',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(129,259,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A15',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(725,339,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A16',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(623,273,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A17',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(11,135,NULL),NULL,NULL));
Insert into XINSHI.ADDRGEOLOC (ADDRID,GEOLOC) values ('A18',MDSYS.SDO_GEOMETRY(2001,NULL,MDSYS.SDO_POINT_TYPE(502,288,NULL),NULL,NULL));
REM INSERTING into XINSHI.CUSTOMERS
SET DEFINE OFF;
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('bill@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('miley@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('angelina@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('brad@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('hope@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('andre@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('nelle@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('jen@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('pit@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('josh@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('tom@csci585.edu','12345');
Insert into XINSHI.CUSTOMERS (USEREMAIL,CUSTPASSWORD) values ('serina@usc.edu','12345');
REM INSERTING into XINSHI.LIKEREVIEW
SET DEFINE OFF;
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('bill@csci585.edu','R1',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('bill@csci585.edu','R4',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('bill@csci585.edu','R9',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('miley@csci585.edu','R3',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('miley@csci585.edu','R5',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('angelina@csci585.edu','R8',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('angelina@csci585.edu','R10',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('brad@csci585.edu','R2',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('brad@csci585.edu','R4',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('hope@csci585.edu','R7',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('andre@csci585.edu','R8',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('andre@csci585.edu','R15',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('nelle@csci585.edu','R2',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('nelle@csci585.edu','R10',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('jen@csci585.edu','R2',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('jen@csci585.edu','R9',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('pit@csci585.edu','R10',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('josh@csci585.edu','R9',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('tom@csci585.edu','R2',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('tom@csci585.edu','R11',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('serina@usc.edu','R9',null);
Insert into XINSHI.LIKEREVIEW (CUSTOMEREMAIL,REVIEWID,LIKETIME) values ('serina@usc.edu','R10',null);
REM INSERTING into XINSHI.MDRT_125D1$
SET DEFINE OFF;
Insert into XINSHI.MDRT_125D1$ (NODE_ID,NODE_LEVEL) values (1,1);
Insert into XINSHI.MDRT_125D1$ (NODE_ID,NODE_LEVEL) values (1,2);
REM INSERTING into XINSHI.ORDERPRODUCTQTY
SET DEFINE OFF;
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O1','Pro1',3);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O1','Pro2',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O2','Pro2',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O2','Pro19',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O3','Pro3',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O3','Pro5',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O4','Pro4',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O5','Pro16',3);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O5','Pro17',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O6','Pro1',3);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O6','Pro5',4);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O7','Pro3',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O7','Pro6',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O8','Pro4',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O8','Pro6',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O9','Pro10',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O10','Pro7',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O10','Pro9',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O11','Pro8',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O11','Pro9',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O12','Pro1',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O12','Pro3',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O13','Pro10',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O14','Pro8',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O14','Pro9',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O15','Pro18',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O16','Pro18',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O17','Pro19',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O18','Pro20',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O19','Pro18',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O20','Pro17',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O21','Pro8',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O21','Pro9',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O22','Pro16',3);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O22','Pro17',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O23','Pro6',3);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O24','Pro7',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O24','Pro9',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O25','Pro8',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O26','Pro1',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O26','Pro2',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O27','Pro3',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O27','Pro4',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O28','Pro4',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O28','Pro5',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O29','Pro9',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O30','Pro1',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O30','Pro20',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O31','Pro8',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O31','Pro9',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O32','Pro4',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O32','Pro5',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O33','Pro8',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O33','Pro11',10);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O34','Pro11',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O34','Pro12',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O35','Pro8',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O36','Pro7',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O37','Pro18',5);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O38','Pro16',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O39','Pro19',3);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O40','Pro12',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O41','Pro18',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O42','Pro17',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O43','Pro19',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O44','Pro11',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O45','Pro12',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O46','Pro16',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O46','Pro17',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O47','Pro15',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O48','Pro14',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O49','Pro16',1);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O49','Pro19',2);
Insert into XINSHI.ORDERPRODUCTQTY (ORDERID,PRODUCTID,QUANTITY) values ('O50','Pro20',1);
REM INSERTING into XINSHI.ORDERS
SET DEFINE OFF;
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O1',to_date('07-JUN-13','DD-MON-RR'),to_date('10-JUN-13','DD-MON-RR'),to_date('11-JUN-13','DD-MON-RR'),null,'12345678',to_date('06-JUN-13','DD-MON-RR'),null,null,null,null,'bill@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O2',to_date('08-JUN-13','DD-MON-RR'),to_date('11-JUN-13','DD-MON-RR'),to_date('12-JUN-13','DD-MON-RR'),null,'12345679',to_date('07-JUN-13','DD-MON-RR'),null,null,null,null,'bill@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O3',to_date('09-JUN-13','DD-MON-RR'),to_date('12-JUN-13','DD-MON-RR'),to_date('13-JUN-13','DD-MON-RR'),null,'12345680',to_date('08-JUN-13','DD-MON-RR'),null,null,null,null,'bill@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O4',to_date('10-JUN-13','DD-MON-RR'),to_date('13-JUN-13','DD-MON-RR'),to_date('14-JUN-13','DD-MON-RR'),null,'12345681',to_date('09-JUN-13','DD-MON-RR'),null,null,null,null,'bill@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O5',to_date('11-JUN-13','DD-MON-RR'),to_date('14-JUN-13','DD-MON-RR'),to_date('15-JUN-13','DD-MON-RR'),null,'12345682',to_date('10-JUN-13','DD-MON-RR'),null,null,null,null,'bill@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O6',to_date('12-JUN-13','DD-MON-RR'),to_date('15-JUN-13','DD-MON-RR'),to_date('16-JUN-13','DD-MON-RR'),null,'12345683',to_date('11-JUN-13','DD-MON-RR'),null,null,null,null,'miley@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O7',to_date('13-JUN-13','DD-MON-RR'),to_date('16-JUN-13','DD-MON-RR'),to_date('17-JUN-13','DD-MON-RR'),null,'12345684',to_date('12-JUN-13','DD-MON-RR'),null,null,null,null,'miley@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O8',to_date('14-JUN-13','DD-MON-RR'),to_date('17-JUN-13','DD-MON-RR'),to_date('18-JUN-13','DD-MON-RR'),null,'12345685',to_date('13-JUN-13','DD-MON-RR'),null,null,null,null,'miley@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O9',to_date('15-JUN-13','DD-MON-RR'),to_date('18-JUN-13','DD-MON-RR'),to_date('19-JUN-13','DD-MON-RR'),null,'12345686',to_date('14-JUN-13','DD-MON-RR'),null,null,null,null,'miley@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O10',to_date('16-JUN-13','DD-MON-RR'),to_date('19-JUN-13','DD-MON-RR'),to_date('20-JUN-13','DD-MON-RR'),null,'12345687',to_date('15-JUN-13','DD-MON-RR'),null,null,null,null,'miley@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O11',to_date('17-JUN-13','DD-MON-RR'),to_date('20-JUN-13','DD-MON-RR'),to_date('21-JUN-13','DD-MON-RR'),null,'12345688',to_date('16-JUN-13','DD-MON-RR'),null,null,null,null,'angelina@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O12',to_date('18-JUN-13','DD-MON-RR'),to_date('21-JUN-13','DD-MON-RR'),to_date('22-JUN-13','DD-MON-RR'),null,'12345689',to_date('17-JUN-13','DD-MON-RR'),null,null,null,null,'angelina@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O13',to_date('19-JUN-13','DD-MON-RR'),to_date('22-JUN-13','DD-MON-RR'),to_date('23-JUN-13','DD-MON-RR'),null,'12345690',to_date('18-JUN-13','DD-MON-RR'),null,null,null,null,'angelina@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O14',to_date('20-JUN-13','DD-MON-RR'),to_date('23-JUN-13','DD-MON-RR'),to_date('24-JUN-13','DD-MON-RR'),null,'12345691',to_date('19-JUN-13','DD-MON-RR'),null,null,null,null,'angelina@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O15',to_date('21-JUN-13','DD-MON-RR'),to_date('24-JUN-13','DD-MON-RR'),to_date('25-JUN-13','DD-MON-RR'),null,'12345692',to_date('20-JUN-13','DD-MON-RR'),null,null,null,null,'pit@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O16',to_date('22-JUN-13','DD-MON-RR'),to_date('25-JUN-13','DD-MON-RR'),to_date('26-JUN-13','DD-MON-RR'),null,'12345693',to_date('21-JUN-13','DD-MON-RR'),null,null,null,null,'brad@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O17',to_date('23-JUN-13','DD-MON-RR'),to_date('26-JUN-13','DD-MON-RR'),to_date('27-JUN-13','DD-MON-RR'),null,'12345694',to_date('22-JUN-13','DD-MON-RR'),null,null,null,null,'brad@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O18',to_date('24-JUN-13','DD-MON-RR'),to_date('27-JUN-13','DD-MON-RR'),to_date('28-JUN-13','DD-MON-RR'),null,'12345695',to_date('23-JUN-13','DD-MON-RR'),null,null,null,null,'brad@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O19',to_date('25-JUN-13','DD-MON-RR'),to_date('28-JUN-13','DD-MON-RR'),to_date('29-JUN-13','DD-MON-RR'),null,'12345696',to_date('24-JUN-13','DD-MON-RR'),null,null,null,null,'brad@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O20',to_date('26-JUN-13','DD-MON-RR'),to_date('29-JUN-13','DD-MON-RR'),to_date('30-JUN-13','DD-MON-RR'),null,'12345697',to_date('25-JUN-13','DD-MON-RR'),null,null,null,null,'brad@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O21',to_date('27-JUN-13','DD-MON-RR'),to_date('30-JUN-13','DD-MON-RR'),to_date('01-JUL-13','DD-MON-RR'),null,'12345698',to_date('26-JUN-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O22',to_date('28-JUN-13','DD-MON-RR'),to_date('01-JUL-13','DD-MON-RR'),to_date('02-JUL-13','DD-MON-RR'),null,'12345699',to_date('27-JUN-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O23',to_date('29-JUN-13','DD-MON-RR'),to_date('02-JUL-13','DD-MON-RR'),to_date('03-JUL-13','DD-MON-RR'),null,'12345700',to_date('28-JUN-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O24',to_date('30-JUN-13','DD-MON-RR'),to_date('03-JUL-13','DD-MON-RR'),to_date('04-JUL-13','DD-MON-RR'),null,'12345701',to_date('29-JUN-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O25',to_date('01-JUL-13','DD-MON-RR'),to_date('04-JUL-13','DD-MON-RR'),to_date('05-JUL-13','DD-MON-RR'),null,'12345702',to_date('30-JUN-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O26',to_date('02-JUL-13','DD-MON-RR'),to_date('05-JUL-13','DD-MON-RR'),to_date('06-JUL-13','DD-MON-RR'),null,'12345703',to_date('01-JUL-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O27',to_date('03-JUL-13','DD-MON-RR'),to_date('06-JUL-13','DD-MON-RR'),to_date('07-JUL-13','DD-MON-RR'),null,'12345704',to_date('02-JUL-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O28',to_date('04-JUL-13','DD-MON-RR'),to_date('07-JUL-13','DD-MON-RR'),to_date('08-JUL-13','DD-MON-RR'),null,'12345705',to_date('03-JUL-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O29',to_date('05-JUL-13','DD-MON-RR'),to_date('08-JUL-13','DD-MON-RR'),to_date('09-JUL-13','DD-MON-RR'),null,'12345706',to_date('04-JUL-13','DD-MON-RR'),null,null,null,null,'hope@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O30',to_date('06-JUL-13','DD-MON-RR'),to_date('09-JUL-13','DD-MON-RR'),to_date('10-JUL-13','DD-MON-RR'),null,'12345707',to_date('05-JUL-13','DD-MON-RR'),null,null,null,null,'andre@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O31',to_date('07-JUL-13','DD-MON-RR'),to_date('10-JUL-13','DD-MON-RR'),to_date('11-JUL-13','DD-MON-RR'),null,'12345708',to_date('06-JUL-13','DD-MON-RR'),null,null,null,null,'andre@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O32',to_date('08-JUL-13','DD-MON-RR'),to_date('11-JUL-13','DD-MON-RR'),to_date('12-JUL-13','DD-MON-RR'),null,'12345709',to_date('07-JUL-13','DD-MON-RR'),null,null,null,null,'nelle@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O33',to_date('09-JUL-13','DD-MON-RR'),to_date('12-JUL-13','DD-MON-RR'),to_date('13-JUL-13','DD-MON-RR'),null,'12345710',to_date('08-JUL-13','DD-MON-RR'),null,null,null,null,'nelle@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O34',to_date('10-JUL-13','DD-MON-RR'),to_date('13-JUL-13','DD-MON-RR'),to_date('14-JUL-13','DD-MON-RR'),null,'12345711',to_date('09-JUL-13','DD-MON-RR'),null,null,null,null,'jen@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O35',to_date('11-JUL-13','DD-MON-RR'),to_date('14-JUL-13','DD-MON-RR'),to_date('15-JUL-13','DD-MON-RR'),null,'12345712',to_date('10-JUL-13','DD-MON-RR'),null,null,null,null,'jen@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O36',to_date('12-JUL-13','DD-MON-RR'),to_date('15-JUL-13','DD-MON-RR'),to_date('16-JUL-13','DD-MON-RR'),null,'12345713',to_date('11-JUL-13','DD-MON-RR'),null,null,null,null,'jen@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O37',to_date('13-JUL-13','DD-MON-RR'),to_date('16-JUL-13','DD-MON-RR'),to_date('17-JUL-13','DD-MON-RR'),null,'12345714',to_date('12-JUL-13','DD-MON-RR'),null,null,null,null,'pit@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O38',to_date('14-JUL-13','DD-MON-RR'),to_date('17-JUL-13','DD-MON-RR'),to_date('18-JUL-13','DD-MON-RR'),null,'12345715',to_date('13-JUL-13','DD-MON-RR'),null,null,null,null,'pit@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O39',to_date('15-JUL-13','DD-MON-RR'),to_date('18-JUL-13','DD-MON-RR'),to_date('19-JUL-13','DD-MON-RR'),null,'12345716',to_date('14-JUL-13','DD-MON-RR'),null,null,null,null,'pit@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O40',to_date('16-JUL-13','DD-MON-RR'),to_date('19-JUL-13','DD-MON-RR'),to_date('20-JUL-13','DD-MON-RR'),null,'12345717',to_date('15-JUL-13','DD-MON-RR'),null,null,null,null,'pit@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O41',to_date('17-JUL-13','DD-MON-RR'),to_date('20-JUL-13','DD-MON-RR'),to_date('21-JUL-13','DD-MON-RR'),null,'12345718',to_date('16-JUL-13','DD-MON-RR'),null,null,null,null,'josh@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O42',to_date('18-JUL-13','DD-MON-RR'),to_date('21-JUL-13','DD-MON-RR'),to_date('22-JUL-13','DD-MON-RR'),null,'12345719',to_date('17-JUL-13','DD-MON-RR'),null,null,null,null,'josh@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O43',to_date('19-JUL-13','DD-MON-RR'),to_date('22-JUL-13','DD-MON-RR'),to_date('23-JUL-13','DD-MON-RR'),null,'12345720',to_date('18-JUL-13','DD-MON-RR'),null,null,null,null,'josh@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O44',to_date('20-JUL-13','DD-MON-RR'),to_date('23-JUL-13','DD-MON-RR'),to_date('24-JUL-13','DD-MON-RR'),null,'12345721',to_date('19-JUL-13','DD-MON-RR'),null,null,null,null,'tom@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O45',to_date('21-JUL-13','DD-MON-RR'),to_date('24-JUL-13','DD-MON-RR'),to_date('25-JUL-13','DD-MON-RR'),null,'12345722',to_date('20-JUL-13','DD-MON-RR'),null,null,null,null,'tom@csci585.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O46',to_date('22-JUL-13','DD-MON-RR'),to_date('25-JUL-13','DD-MON-RR'),to_date('26-JUL-13','DD-MON-RR'),null,'12345723',to_date('21-JUL-13','DD-MON-RR'),null,null,null,null,'serina@usc.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O47',to_date('23-JUL-13','DD-MON-RR'),to_date('26-JUL-13','DD-MON-RR'),to_date('27-JUL-13','DD-MON-RR'),null,'12345724',to_date('22-JUL-13','DD-MON-RR'),null,null,null,null,'serina@usc.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O48',to_date('24-JUL-13','DD-MON-RR'),to_date('27-JUL-13','DD-MON-RR'),to_date('28-JUL-13','DD-MON-RR'),null,'12345725',to_date('23-JUL-13','DD-MON-RR'),null,null,null,null,'serina@usc.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O49',to_date('25-JUL-13','DD-MON-RR'),to_date('28-JUL-13','DD-MON-RR'),to_date('29-JUL-13','DD-MON-RR'),null,'12345726',to_date('24-JUL-13','DD-MON-RR'),null,null,null,null,'serina@usc.edu',null);
Insert into XINSHI.ORDERS (ORDERID,SHIPPEDTIME,ESTIARRITIME,SIGNEDTIME,TOTALPRICE,TRACKINGNUM,PLACETIME,ACCNUM,EXPDATE,CSC,FILLTIME,CUSTOMEREMAIL,SHIPADDR) values ('O50',to_date('26-JUL-13','DD-MON-RR'),to_date('29-JUL-13','DD-MON-RR'),to_date('30-JUL-13','DD-MON-RR'),null,'12345727',to_date('25-JUL-13','DD-MON-RR'),null,null,null,null,'serina@usc.edu',null);
REM INSERTING into XINSHI.PHOTOS
SET DEFINE OFF;
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho1',to_date('12-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho2',to_date('13-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho3',to_date('14-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho4',to_date('15-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho5',to_date('16-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho6',to_date('17-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho7',to_date('18-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho8',to_date('19-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho9',to_date('20-DEC-12','DD-MON-RR'),'profile photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho13',to_date('24-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho14',to_date('25-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho15',to_date('26-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho16',to_date('27-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho17',to_date('28-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho18',to_date('29-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho19',to_date('30-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho20',to_date('31-DEC-12','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho21',to_date('01-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho22',to_date('02-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho23',to_date('03-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho24',to_date('04-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho25',to_date('05-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho26',to_date('06-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho27',to_date('07-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho28',to_date('08-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho29',to_date('09-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho30',to_date('10-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho31',to_date('11-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho32',to_date('12-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho33',to_date('13-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho34',to_date('14-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho35',to_date('15-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho36',to_date('16-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho37',to_date('17-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho38',to_date('18-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho39',to_date('19-JAN-13','DD-MON-RR'),'product photo');
Insert into XINSHI.PHOTOS (PHOTOID,TAKEN_TIME,DESCRIPTION) values ('Pho40',to_date('20-JAN-13','DD-MON-RR'),'product photo');
REM INSERTING into XINSHI.PRODUCTPHOTO
SET DEFINE OFF;
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro1','Pho13');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro1','Pho14');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro1','Pho15');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro10','Pho28');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro10','Pho29');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro10','Pho30');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro11','Pho31');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro12','Pho32');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro13','Pho33');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro14','Pho34');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro15','Pho35');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro16','Pho36');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro17','Pho37');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro18','Pho38');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro19','Pho39');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro2','Pho16');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro2','Pho17');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro20','Pho40');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro3','Pho18');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro3','Pho19');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro4','Pho20');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro5','Pho21');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro6','Pho22');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro7','Pho23');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro7','Pho24');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro8','Pho25');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro9','Pho26');
Insert into XINSHI.PRODUCTPHOTO (PRODUCTID,PHOTOID) values ('Pro9','Pho27');
REM INSERTING into XINSHI.PRODUCTS
SET DEFINE OFF;
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro1','Tommy Bahama ''Sail Hawaii'' Cover-Up T-Shirt Dress','Clothing','Tommy Bahama',88,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro2','Nike ''Pro Hyperwarm'' Training Top','Clothing','Nike',65,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro3','Olive & Oak Faux Leather Sleeve Collarless Jacket','Clothing','Olive & Oak',102,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro4','Hard Tail ''Frolic'' Asymmetric Top','Clothing','Hard Tail',78,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro5','Gallery Turnkey Quilted Jacket ','Clothing','Gallery',116,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro6','butter LONDON WINK Mascara','Beauty','butter LONDON',20,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro7','Tarte LipSurgence Natural Matte Lip Tint','Beauty','butter LONDON',24,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro8','Dramatically Different Moisturizing Gel','Beauty','Clinique',26,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro9','Liquid Facial Soap','Beauty','Clinique',17,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro10','Advanced Night Repair Synchronized Recovery Complex II Collection','Beauty','Estee Lauder',120,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro11','Sparkle Paper Towels, Print, 12 Large Rolls','Home & Kitchen','Sparkle',12,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro12','Duster Brush','Home & Kitchen','Sparkle',9,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro13','Lasko 5624 Low Profile Silent Room Heater, Black','Home & Kitchen','Lasko',52,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro14','Lasko 2004W 2-Speed Clip Fan, 6-Inch, White','Home & Kitchen','Lasko',15,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro15','Coaster Futon Sofa Bed with Removable Arm Rests, Brown Vinyl','Home & Kitchen','Coaster Home Furnishings',330,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro16','Dell Inspiron i660s-1231BK Desktop','Electronics','Dell',120,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro17','Apple Wireless Keyboard MC184LL/B','Electronics','Apple',65,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro18','Sony HDRCX240/L Video Camera with 2.7-Inch LCD','Electronics','Sony',228,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro19','Sony SmartWatch US version 1 Android Bluetooth USB Retail Box','Electronics','Sony',75,100);
Insert into XINSHI.PRODUCTS (PRODUCTID,PRONAME,PROCATEGORY,BRAND,PRICE,STOCKQTY) values ('Pro20','Apple iPod touch 16GB White','Electronics','Apple',215,100);
REM INSERTING into XINSHI.PRODUCTSELLER
SET DEFINE OFF;
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('al@csci585.edu','Pro1',99);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('al@csci585.edu','Pro2',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('steve@csci585.edu','Pro3',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('steve@csci585.edu','Pro4',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('al@csci585.edu','Pro5',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro6',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro7',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro8',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro9',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('steve@csci585.edu','Pro10',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro11',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro12',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('miley@csci585.edu','Pro13',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('miley@csci585.edu','Pro14',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('bill@csci585.edu','Pro15',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('miley@csci585.edu','Pro16',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('miley@csci585.edu','Pro17',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('al@csci585.edu','Pro18',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('miley@csci585.edu','Pro19',100);
Insert into XINSHI.PRODUCTSELLER (SELLEREMAIL,PRODUCTID,QUANTITY) values ('al@csci585.edu','Pro20',100);
REM INSERTING into XINSHI.REVIEWS
SET DEFINE OFF;
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R1','angelina@csci585.edu',4,'A good product','Pro1',to_date('01-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R2','jen@csci585.edu',2,'Fine','Pro6',to_date('02-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R3','angelina@csci585.edu',3,'Reasonable','Pro3',to_date('03-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R4','brad@csci585.edu',4,'Good quanlity and cheap price','Pro12',to_date('04-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R5','andre@csci585.edu',5,'A great product','Pro13',to_date('05-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R6','jen@csci585.edu',4,'A good product','Pro7',to_date('06-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R7','angelina@csci585.edu',2,'Just so so','Pro14',to_date('07-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R8','andre@csci585.edu',3,'That''s OK','Pro2',to_date('08-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R9','jen@csci585.edu',4,'A good product','Pro16',to_date('09-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R10','brad@csci585.edu',3,'fine','Pro4',to_date('10-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R11','angelina@csci585.edu',2,'Just so so','Pro17',to_date('11-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R12','brad@csci585.edu',5,'A wonderful product with cheap price','Pro8',to_date('12-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R13','brad@csci585.edu',3,'It works fine','Pro5',to_date('13-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R14','miley@csci585.edu',4,'It is great!','Pro15',to_date('14-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R15','josh@csci585.edu',5,'A great product','Pro1',to_date('15-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R16','hope@csci585.edu',4,'good','Pro3',to_date('16-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R17','angelina@csci585.edu',2,'Just so so','Pro19',to_date('17-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R18','brad@csci585.edu',3,'That''s OK','Pro18',to_date('18-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R19','hope@csci585.edu',4,'Good quanlity and cheap price','Pro4',to_date('19-JAN-14','DD-MON-RR'));
Insert into XINSHI.REVIEWS (REVIEWID,AUTHORID,RATING,COMTENT,PRODUCTID,POSTTIME) values ('R20','angelina@csci585.edu',5,'A wonderful product with cheap price','Pro4',to_date('20-JAN-14','DD-MON-RR'));
REM INSERTING into XINSHI.SELLERS
SET DEFINE OFF;
Insert into XINSHI.SELLERS (USEREMAIL,SELLERPASSWORD) values ('al@csci585.edu','12345');
Insert into XINSHI.SELLERS (USEREMAIL,SELLERPASSWORD) values ('steve@csci585.edu','12345');
Insert into XINSHI.SELLERS (USEREMAIL,SELLERPASSWORD) values ('bill@csci585.edu','12345');
Insert into XINSHI.SELLERS (USEREMAIL,SELLERPASSWORD) values ('miley@csci585.edu','12345');
REM INSERTING into XINSHI.USERS
SET DEFINE OFF;
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('bill@csci585.edu',to_date('28-OCT-55','DD-MON-RR'),null,null,'Bill','Gates','1234-5678-2564-3214',to_date('01-JUN-15','DD-MON-RR'),'888','Bill1','M',to_date('29-JAN-14','DD-MON-RR'),'Pho3','A3');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('miley@csci585.edu',to_date('23-NOV-92','DD-MON-RR'),null,null,'Miley','Cyrus','1234-5678-2564-3215',to_date('01-JUL-15','DD-MON-RR'),'555','Miley1','M',to_date('30-JAN-14','DD-MON-RR'),'Pho4','A4');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('angelina@csci585.edu',to_date('04-JUN-75','DD-MON-RR'),null,null,'Angelina','Jolie','1234-5678-2564-3210',to_date('01-FEB-15','DD-MON-RR'),'254','Angelina1','F',to_date('25-JAN-14','DD-MON-RR'),null,'A5');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('brad@csci585.edu',to_date('18-DEC-63','DD-MON-RR'),null,null,'Brad','Pitt','1234-5678-2564-3211',to_date('01-MAR-15','DD-MON-RR'),'612','Brad1','M',to_date('26-JAN-14','DD-MON-RR'),null,'A6');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('hope@csci585.edu',to_date('20-JUL-81','DD-MON-RR'),null,null,'Hope','Solo','1234-5678-2564-3216',to_date('01-AUG-15','DD-MON-RR'),'212','Hope1','F',to_date('30-JAN-14','DD-MON-RR'),null,'A7');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('andre@csci585.edu',to_date('29-APR-70','DD-MON-RR'),null,null,'Andre','Agassi','1234-5678-2564-3217',to_date('01-SEP-15','DD-MON-RR'),'101','Andre1','F',to_date('31-JAN-14','DD-MON-RR'),'Pho7','A8');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('nelle@csci585.edu',to_date('12-SEP-55','DD-MON-RR'),null,null,'Nelle','Lee','1234-5678-2564-3218',to_date('01-OCT-15','DD-MON-RR'),'505','Nelle1','F',to_date('01-FEB-14','DD-MON-RR'),'Pho8','A9');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('jen@csci585.edu',to_date('11-FEB-69','DD-MON-RR'),null,null,'Jennifer','Aniston','1234-5678-2564-3219',to_date('01-NOV-15','DD-MON-RR'),'747','Jennifer1','F',to_date('02-FEB-14','DD-MON-RR'),null,'A10');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('pit@csci585.edu',to_date('12-AUG-71','DD-MON-RR'),null,null,'Pit','Sampras','1234-5678-2564-3220',to_date('01-DEC-15','DD-MON-RR'),'845','Pit1','M',to_date('03-FEB-14','DD-MON-RR'),null,'A11');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('josh@csci585.edu',to_date('29-JUL-74','DD-MON-RR'),null,null,'Josh','Radnor','1234-5678-2564-3221',to_date('01-JAN-16','DD-MON-RR'),'988','Josh1','M',to_date('04-FEB-14','DD-MON-RR'),null,'A12');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('tom@csci585.edu',to_date('03-JUL-62','DD-MON-RR'),null,null,'Tom','Cruise','1234-5678-2564-3222',to_date('01-FEB-16','DD-MON-RR'),'669','Tom1','M',to_date('05-FEB-14','DD-MON-RR'),'Pho6','A13');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('serina@usc.edu',to_date('26-SEP-81','DD-MON-RR'),null,null,'Serena','Williams','1234-5678-2564-3223',to_date('01-MAR-16','DD-MON-RR'),'636','Serena1','M',to_date('06-FEB-14','DD-MON-RR'),'Pho5','A14');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('al@csci585.edu',to_date('25-APR-70','DD-MON-RR'),null,null,'Alfredo','Pacino','1234-5678-2564-3212',to_date('01-APR-15','DD-MON-RR'),'213','Alfredo1','F',to_date('27-JAN-14','DD-MON-RR'),'Pho1','A1');
Insert into XINSHI.USERS (USEREMAIL,BIRTHDATE,BIRTHMONTH,AGE,FNAME,LNAME,ACCNUMBER,EXPDATE,CSC,NICKNAME,GENDER,JOINTIME,PHOTOID,ADDRID) values ('steve@csci585.edu',to_date('24-FEB-55','DD-MON-RR'),null,null,'Steve','Jobs','1234-5678-2564-3213',to_date('01-MAY-15','DD-MON-RR'),'545','Steve1','M',to_date('28-JAN-14','DD-MON-RR'),'Pho2','A2');
--------------------------------------------------------
--  DDL for Index SYS_C0011433
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011433" ON "ADDRESSES" ("ADDRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011462
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011462" ON "ADDRGEOLOC" ("ADDRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDEX_ADDRGEO
--------------------------------------------------------

  CREATE INDEX "INDEX_ADDRGEO" ON "ADDRGEOLOC" ("GEOLOC") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011440" ON "CUSTOMERS" ("USEREMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011450" ON "LIKEREVIEW" ("CUSTOMEREMAIL", "REVIEWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011459
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011459" ON "ORDERPRODUCTQTY" ("ORDERID", "PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011447
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011447" ON "ORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011431
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011431" ON "PHOTOS" ("PHOTOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011456
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011456" ON "PRODUCTPHOTO" ("PRODUCTID", "PHOTOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011432
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011432" ON "PRODUCTS" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011453
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011453" ON "PRODUCTSELLER" ("SELLEREMAIL", "PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011443
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011443" ON "REVIEWS" ("REVIEWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011438
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011438" ON "SELLERS" ("USEREMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011435
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011435" ON "USERS" ("USEREMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESSES
--------------------------------------------------------

  ALTER TABLE "ADDRESSES" ADD PRIMARY KEY ("ADDRID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRGEOLOC
--------------------------------------------------------

  ALTER TABLE "ADDRGEOLOC" ADD PRIMARY KEY ("ADDRID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "CUSTOMERS" ADD PRIMARY KEY ("USEREMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIKEREVIEW
--------------------------------------------------------

  ALTER TABLE "LIKEREVIEW" ADD PRIMARY KEY ("CUSTOMEREMAIL", "REVIEWID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERPRODUCTQTY
--------------------------------------------------------

  ALTER TABLE "ORDERPRODUCTQTY" ADD PRIMARY KEY ("ORDERID", "PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ORDERS" MODIFY ("CUSTOMEREMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHOTOS
--------------------------------------------------------

  ALTER TABLE "PHOTOS" ADD PRIMARY KEY ("PHOTOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTPHOTO
--------------------------------------------------------

  ALTER TABLE "PRODUCTPHOTO" ADD PRIMARY KEY ("PRODUCTID", "PHOTOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "PRODUCTS" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTSELLER
--------------------------------------------------------

  ALTER TABLE "PRODUCTSELLER" ADD PRIMARY KEY ("SELLEREMAIL", "PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "REVIEWS" MODIFY ("AUTHORID" NOT NULL ENABLE);
 
  ALTER TABLE "REVIEWS" ADD PRIMARY KEY ("REVIEWID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELLERS
--------------------------------------------------------

  ALTER TABLE "SELLERS" ADD PRIMARY KEY ("USEREMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" MODIFY ("ADDRID" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" ADD PRIMARY KEY ("USEREMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRGEOLOC
--------------------------------------------------------

  ALTER TABLE "ADDRGEOLOC" ADD FOREIGN KEY ("ADDRID")
	  REFERENCES "ADDRESSES" ("ADDRID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "CUSTOMERS" ADD FOREIGN KEY ("USEREMAIL")
	  REFERENCES "USERS" ("USEREMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKEREVIEW
--------------------------------------------------------

  ALTER TABLE "LIKEREVIEW" ADD FOREIGN KEY ("CUSTOMEREMAIL")
	  REFERENCES "CUSTOMERS" ("USEREMAIL") ENABLE;
 
  ALTER TABLE "LIKEREVIEW" ADD FOREIGN KEY ("REVIEWID")
	  REFERENCES "REVIEWS" ("REVIEWID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERPRODUCTQTY
--------------------------------------------------------

  ALTER TABLE "ORDERPRODUCTQTY" ADD FOREIGN KEY ("ORDERID")
	  REFERENCES "ORDERS" ("ORDERID") ENABLE;
 
  ALTER TABLE "ORDERPRODUCTQTY" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("CUSTOMEREMAIL")
	  REFERENCES "CUSTOMERS" ("USEREMAIL") ENABLE;
 
  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("SHIPADDR")
	  REFERENCES "ADDRESSES" ("ADDRID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTPHOTO
--------------------------------------------------------

  ALTER TABLE "PRODUCTPHOTO" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") ENABLE;
 
  ALTER TABLE "PRODUCTPHOTO" ADD FOREIGN KEY ("PHOTOID")
	  REFERENCES "PHOTOS" ("PHOTOID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTSELLER
--------------------------------------------------------

  ALTER TABLE "PRODUCTSELLER" ADD FOREIGN KEY ("SELLEREMAIL")
	  REFERENCES "SELLERS" ("USEREMAIL") ENABLE;
 
  ALTER TABLE "PRODUCTSELLER" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "REVIEWS" ADD FOREIGN KEY ("AUTHORID")
	  REFERENCES "CUSTOMERS" ("USEREMAIL") ENABLE;
 
  ALTER TABLE "REVIEWS" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELLERS
--------------------------------------------------------

  ALTER TABLE "SELLERS" ADD FOREIGN KEY ("USEREMAIL")
	  REFERENCES "USERS" ("USEREMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD FOREIGN KEY ("ADDRID")
	  REFERENCES "ADDRESSES" ("ADDRID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USERS" ADD FOREIGN KEY ("PHOTOID")
	  REFERENCES "PHOTOS" ("PHOTOID") ON DELETE CASCADE ENABLE;
